# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Clean cache"
  lane :gradleClean do
    gradle(task: "clean")
  end

  desc "Build app"
  lane :gradleBuild do
    gradle(task: "assembleDebug")
  end

  desc "Deploy firebase"
  lane :deploy do |params|
    vCode = ENV["VER_CODE"]
    vName = ENV["VER_NAME"]
    releaseNote = ENV["RELEASE_NOTE"]
    gradle(task: "assembleDebug")
    release = firebase_app_distribution(
        app: "1:123456789:android:abcd1234",
        testers: "tester1@company.com",
        release_notes: releaseNote
    )
end
